export const prescriptionDTO = (row) => ({
  id: row.id,
  prescription_number: row.prescription_number,
  patient_id: row.patient_id,
  doctor_id: row.doctor_id,
  clinic_id: row.clinic_id,
  notes: row.notes,
  issued_date: row.issued_date,
  valid_until: row.valid_until,
  created_by: row.created_by,
  doctor_name: row.doctor_name,
  doctor_specialty: row.doctor_specialty,
  patient_name: row.patient_name,
  patient_dni: row.patient_dni,
  created_at: row.created_at,
  items: (row.items || []).map(item => ({
    id: item.id,
    medication_name: item.medication_name,
    dosage: item.dosage,
    frequency: item.frequency,
    duration: item.duration,
    instructions: item.instructions,
    sort_order: item.sort_order,
  })),
});
